name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
          check-latest: true

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.1
          args: --timeout 30m ./...
